'use strict';var ox={TAB:0,ig:1,cj:2},px=function(a){cb("MediaRouter.CastStreaming.Start.Success",a,ox)};var qx=Ja("mr.mirror.cast.LogUploader"),sx=function(a,b,c){rx("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?stbtiq="+b:""},rx=function(a,b,c,d){if(0==b.size)u(qx,"Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);wj("https://clients2.google.com/cr/report",function(a){a=a.target;var b=null;Gj(a)?(b=Hj(a),u(qx,"Upload to Crash succeeded: "+
b)):u(qx,"Upload to Crash failed. HTTP status: "+a.Ba());d&&d(b)},"POST",e,void 0,3E4)}};var tx=function(){this.a=0;Qf(this)},vx=function(){ux||(ux=new tx);return ux},wx=function(){var a=vx(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.a&&c&&d-a.a<c?!1:Math.random()<b.fraction};tx.prototype.ea=function(){return"mirror.cast.LogUtils"};tx.prototype.ua=function(){return[void 0,{lastAutoSubmitMillis:this.a}]};tx.prototype.xa=function(){var a=Of(this);this.a=a&&a.lastAutoSubmitMillis||0};var ux=null;Ja("mr.mirror.cast.LogUtils");var xx=Ja("mr.NetworkUtils"),yx=function(a,b){return ue?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(t(xx,"Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(u(xx,"TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var zx=function(){this.a=Promise.resolve(1)},Bx=function(a,b,c){return Ax(a,function(a){return a==b},c)},Cx=function(a,b){var c=[3,4];return Ax(a,function(a){return-1!=c.indexOf(a)},b)},Dx=function(a,b){a.a=a.a.catch(function(){return 1});return Ax(a,function(){return!0},b)},Ax=function(a,b,c){var d,e,f=new Promise(function(a,b){d=a;e=b});a.a=a.a.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new Ex(a);try{var g=c(f)}catch(y){g=
Promise.reject(y)}return g.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.a)throw Error("A prior operation that started at "+(a+" did not complete."));return f.a})},function(a){e(a);throw a;});return f},Ex=function(a){this.b=a;this.a=null},Fx=function(a,b){a.a="number"===typeof b?b:a.b};var Gx={Mp:"OFFER",Im:"ANSWER",iq:"PRESENTATION",ao:"GET_STATUS",Wq:"STATUS_RESPONSE",Zn:"GET_CAPABILITIES",bn:"CAPABILITIES_RESPONSE",Iq:"RPC"};var Hx=function(){this.capabilities=this.status=this.a=this.error=this.rpc=this.result=this.type=this.b=this.sessionId=null},Kx=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;Ix(JSON.parse(a),function(a){b=Jx(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},Jx=function(a){var b=new Hx;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Lx(a.seqNum,function(a){b.b=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=ia(Object.keys(Gx)),e=d.next();!e.done;e=d.next())if(Gx[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(la(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}Ix(a.error,function(a){b.error=Mx(a)},function(){throw Error('"error" must be an Object');});Ix(a.answer,function(a){b.a=Nx(a)},function(){throw Error('"answer" must be an Object');});Ix(a.status,function(a){b.status=Ox(a)},function(){throw Error('"status" must be an Object');
});Ix(a.capabilities,function(a){b.capabilities=Px(a)},function(){throw Error('"capabilities" must be an Object');});return b},Ix=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Lx=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Qx=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},Rx=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},Sx=function(){this.l=null;this.a=[];this.b=
[];this.f=this.g=this.h=null},Nx=function(a){var b=new Sx;Lx(a.udpPort,function(a){b.l=a},function(){throw Error('"answer.udpPort" must be a number');});Qx(a.sendIndexes,function(a){b.a=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Qx(a.ssrcs,function(a){b.b=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.h=String(a.IV));"receiverGetStatus"in a&&(b.g="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.f=String(a.castMode));
return b},Tx=function(){this.details=this.description=this.code=null},Mx=function(a){var b=new Tx;Lx(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));Ix(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},Ux=function(){this.b=this.a=null},Ox=function(a){var b=new Ux;Lx(a.wifiSnr,function(a){b.a=a},function(){throw Error('"status.wifiSnr" must be a number');
});Qx(a.wifiSpeed,function(a){b.b=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Vx=function(){this.b=this.a=null},Px=function(a){var b=new Vx;Rx(a.mediaCaps,function(a){b.a=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.b=a.map(function(a){var b;Ix(a,function(a){b=Wx(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},Xx=function(){this.f=this.m=this.h=this.l=this.w=this.a=this.u=this.b=this.initDataTypes=this.g=null},Wx=function(a){var b=new Xx;"keySystemName"in a&&(b.g=String(a.keySystemName));Rx(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});Rx(a.codecs,function(a){b.b=a},function(){throw Error('"capabilities.codecs" must be an array');});Rx(a.secureCodecs,function(a){b.u=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Rx(a.audioRobustness,function(a){b.a=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});Rx(a.videoRobustness,function(a){b.w=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.l=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.h=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.m=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.f=String(a.distinctiveIdentifierSupport));return b};var Yx=function(a){this.j=Ja("mr.mirror.cast.MessageDispatcher");this.g=a;this.a=null;this.b=new Map;this.f=0},Zx=function(a,b,c){if(a.b.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.b.set(b,c);a.f=0;v(a.j,"Added subscriber for "+b+"-type messages.");a.a||(a.a=vr(a.g),a.a.onMessage=a.l.bind(a))},$x=function(a,b){a.b.delete(b)&&v(a.j,function(){return"Removed subscriber of "+b+"-type messages."});0==a.b.size&&a.a&&(a.a.ta(),a.a=null)};
Yx.prototype.sendMessage=function(a){return this.a?"RPC"==a.type?this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.a.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var ay=function(a,b,c,d,e){var f=null,g=function(){$x(a,c);null!=f&&(clearTimeout(f),f=null)};try{Zx(a,c,function(a){e(a)&&g()})}catch(l){e(null,l);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){g();e(null,a)})};
Yx.prototype.l=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=Kx(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.b.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.f?t(this.j,b):v(this.j,b);++this.f}};var by=chrome.cast.streaming,dy=function(a,b,c,d,e){this.T=a.sessionId;this.w=a.Oe;this.G=a.Pe;this.f=b;this.J=c;this.B=d;this.H=cy(e,"onAnswer",this.w);this.K=cy(e,"onSessionStop",this.w);this.j=Ja("mr.mirror.cast.StreamingLaunchWorkflow");this.s=new zx;this.m=this.v=this.u=this.b=this.a=this.h=this.l=this.g=null};
dy.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof ey,f=b instanceof ey;(e&&b&&!f||f&&a&&!e)&&Cb("Mixing remoting and non-remoting tracks");return Bx(this.s,1,function(e){d.g=a;d.l=b;d.h=c;u(d.j,function(){return"Launching streaming for "+fy(d)+" "+("to a "+d.G+".")});return gy(d).then(d.A.bind(d)).then(function(a){return hy(d,a).then(function(b){d.H();var c=iy(d,b,a);d.a=jy(d,d.a,c);d.b=jy(d,d.b,c);if(!d.a&&!d.b)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.v=!!b.g;d.m=function(a,b){a==d.a?d.h.qc("Audio stream (id="+a+") error: "+b):a==d.b&&d.h.qc("Video stream (id="+a+") error: "+b)};by.rtpStream.onError.addListener(d.m);return ky(d,b,c)})}).then(function(){u(d.j,function(){return"Launched streaming for "+fy(d)});d.h.ud(d);Fx(e,2);return{ik:d.a,lm:d.b}})})};
dy.prototype.stop=function(){var a=this;return Dx(this.s,function(b){if(!a.g&&!a.l)return Fx(b,1),Promise.resolve();u(a.j,function(){return"Stopping streaming for "+fy(a)+"."});a.m&&(by.rtpStream.onError.removeListener(a.m),a.m=null);if(a.h){var c=a.h.Wd();a.h=null}else c=Promise.resolve();return c.then(function(){a.a&&(by.rtpStream.stop(a.a),by.rtpStream.destroy(a.a),a.a=null);a.b&&(by.rtpStream.stop(a.b),by.rtpStream.destroy(a.b),a.b=null);a.u&&(by.udpTransport.destroy(a.u),a.u=null);a.K();u(a.j,
function(){return"Stopped streaming for "+fy(a)+"."});a.g=null;a.l=null;Fx(b,1)})})};
var ly=function(a,b){var c=JSON.stringify(b);return Promise.all([a.a&&new Promise(function(b){return by.rtpStream.getRawEvents(a.a,c,b)}),a.b&&new Promise(function(b){return by.rtpStream.getRawEvents(a.b,c,b)})]).catch(function(b){a.j.error("Unexpected error when calling getRawEvents()",b);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},my=function(a){return Promise.all([a.a&&new Promise(function(b){return by.rtpStream.getStats(a.a,b)}),a.b&&
new Promise(function(b){return by.rtpStream.getStats(a.b,b)})]).catch(function(b){a.j.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[].concat([{}],la(a.filter(function(a){return!!a}))))})},fy=function(a){if(a.g&&a.l)var b="audio+video ";else if(a.g)b="audio-only ";else if(a.l)b="video-only ";else return"stopped";return a.g instanceof ey||a.l instanceof ey?b+"remoting":b+"streaming"},gy=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.g&&(by.rtpStream.destroy(c),c=null);e&&!a.l&&(by.rtpStream.destroy(e),e=null);u(a.j,function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.a=c;a.b=e;a.u=f;b()};a.g instanceof ey||a.l instanceof ey?by.session.create(null,null,c):by.session.create(a.g,a.l,c)})};
dy.prototype.A=function(){for(var a=Ou(),b=Ou(),c=[],d=ia([this.a,this.b]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.a,g=f?127:96,l=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,r=f?48E3:9E4,y=ia(by.rtpStream.getSupportedParams(e)),z=y.next();!z.done;z=y.next())z=z.value,z.payload.payloadType=g,z.payload.maxLatency=this.f.maxLatencyMillis,z.payload.minLatency=this.f.minLatencyMillis,z.payload.animatedLatency=this.f.animatedLatencyMillis,z.payload.ssrc=
l,z.payload.clockRate=r,z.payload.aesKey=a,z.payload.aesIvMask=b,f?(z.payload.channels=2,z.payload.maxBitrate=this.f.audioBitrate,z.payload.maxFrameRate=100):(z.payload.minBitrate=this.f.minVideoBitrate,z.payload.maxBitrate=this.f.maxVideoBitrate,z.payload.maxFrameRate=this.f.maxFrameRate),c.push(new ny(e,z));return c};
var jy=function(a,b,c){b&&!c.some(function(a){return a.jd==b})&&(t(a.j,"Destroying RTP stream not selected by the receiver: id="+b),by.rtpStream.destroy(b),b=null);return b},hy=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,l={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.f.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.f.dscpEnabled&&(l.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(l,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(l,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.f.maxWidth,height:a.f.maxHeight}]});e.push(l)}var r=a.g instanceof ey||a.l instanceof ey?"remoting":"mirroring",y={type:"OFFER",sessionId:a.T,seqNum:Qj(a.J),offer:{castMode:r,receiverGetStatus:!0,supportedStreams:e}};u(a.j,function(){return"Sending OFFER message: "+JSON.stringify(y)});ay(a.B,y,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.a){if(b.b!=y.seqNum)return t(a.j,"Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.a.f)&&e!=r||!e&&"mirroring"!=r)&&a.j.error("Expected receiver to ANSWER with castMode="+r+", but got: "+e);v(a.j,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.a)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},iy=function(a,b,c){if(b.a.length!=b.b.length)return a.j.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.a.length;e={candidate:e.candidate},++f){var g=b.a[f];if(0>g||g>=
c.length)return a.j.error("Receiver selected invalid index ("+g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.candidate=c[g];if(d.some(function(a){return function(b){return b.jd==a.candidate.jd}}(e)))return a.j.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.candidate.params.payload.feedbackSsrc=b.b[g];if(d.some(function(a){return function(b){return b.params.payload.feedbackSsrc==a.candidate.params.payload.feedbackSsrc}}(e)))return a.j.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+
JSON.stringify(b)),[];d.push(e.candidate)}return d},ky=function(a,b,c){var d=null,e=function(){d&&(by.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,g){var f=b.l||2344;u(a.j,function(){return"Starting RTP streams to receiver at "+(a.w+":"+f)+(" for selected offers: "+JSON.stringify(c))});var r=a.u||-1;a.f.dscpEnabled&&(u(a.j,"Enabled DSCP in sender."),by.udpTransport.setOptions(r,{DSCP:!0}));by.udpTransport.setDestination(r,{address:a.w,port:f});var y=new Set(c.map(function(a){return a.jd}));
d=function(a){y.delete(a);0==y.size&&e()};by.rtpStream.onStarted.addListener(d);r=ia(c);for(var z=r.next();!z.done;z=r.next())z=z.value,by.rtpStream.toggleLogging(z.jd,a.f.enableLogging),by.rtpStream.start(z.jd,z.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},cy=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.j.error("Error from testHooks."+b,e)}}:function(){}},ny=function(a,b){this.jd=
a;this.params=b},ey=function(){};var py=function(a,b,c,d,e,f){this.u=a;a=new mojo.SinkCapabilities;a.features=[];a.audio=[];a.video=[mojo.RemotingSinkVideoCapabilities.CODEC_VP8,mojo.RemotingSinkVideoCapabilities.CODEC_H264];this.s=a;this.v=new dy(this.u.Cb,c,d,e,f);this.m=e;this.g=new zx;this.b=new oy;this.h=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.j=Ja("mr.mirror.cast.MediaRemoter");this.a=this.l=this.f=this.w=null};
py.prototype.Ca=function(a,b){var c=this;return Bx(this.g,1,function(d){c.w=a;c.f=b;var e=c.h.createInterfacePtrAndBind();c.h.setConnectionErrorHandler(function(){u(c.j,"Remoter mojo pipe connection error.");qy(c)});c.a=new mojo.MirrorServiceRemotingSourcePtr;var f=Qe(c.u.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.u.mediaSource);u(c.j,"Connecting remoter to browser: tabId="+f);(Te.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,mojo.makeRequest(c.a));
c.a.ptr.setConnectionErrorHandler(function(){u(c.j,"RemotingSource mojo pipe connection error.");qy(c)});c.a.onSinkAvailable(c.s);Fx(d,2);return Promise.resolve()})};var qy=function(a){return Dx(a.g,function(b){a.a&&(a.a.ptr.reset(),a.a=null);var c=a.l;a.l=null;a.f=null;a.w=null;a.h.close();return new Promise(function(d){window.setTimeout(function(){ry(a).then(function(){Fx(b,1);d();c&&c()})},250)})})};py.prototype.Tl=function(a){sy(this.b,a)};py.prototype.sendMessageToSink=py.prototype.Tl;
py.prototype.ud=function(a){this.f&&this.f.ud(a)};py.prototype.Wd=function(){return this.f?this.f.Wd():Promise.resolve()};py.prototype.qc=function(a,b){this.j.error("Error during streaming: "+a,b);if(this.a)this.a.onError();qy(this)};
py.prototype.start=function(){var a=this,b=!1;u(this.j,function(){b=!0;return"Starting next media remoting session."});b&&ty(this.b,function(b){return u(a.j,b)});uy(this.b);Bx(this.g,2,function(b){return(0,a.w)().then(function(c){a.l=c;Zx(a.m,"RPC",function(b){if(b.rpc){var c=a.b;b=b.rpc;c.h&&(++c.m,c.b+=b.length,c.h(b))}});Fx(b,3)}).catch(function(c){return ry(a).then(function(){Fx(b);throw c;})})}).then(function(){u(a.j,"Remoting started successfully.")}).catch(function(b){a.j.error("Failed to start remoting",
b);a.a.onError()})};py.prototype.start=py.prototype.start;
py.prototype.cm=function(a,b){var c=this;return Bx(this.g,3,function(d){return c.v.start(a?new ey:null,b?new ey:null,c).then(function(a){vy(c.b,function(a){return c.m.sendMessage(a)},function(a){c.a.onMessageFromSink(a)});Fx(d,4);return{audio_stream_id:a.ik||-1,video_stream_id:a.lm||-1}}).catch(function(a){return ry(c).then(function(){Fx(d);throw a;})})}).catch(function(a){c.j.error("Failed to start remoting streams",a);qy(c);return{audio_stream_id:-1,video_stream_id:-1}})};
py.prototype.startDataStreams=py.prototype.cm;py.prototype.stop=function(a){var b=this;Cx(this.g,function(c){b.a.onStopped(a);return ry(b).then(function(){u(b.j,"Remoting stopped.");Fx(c,5);(0,b.l)().then(function(){return Bx(b.g,5,function(a){if(b.a)b.a.onSinkAvailable(b.s);Fx(a,2);return Promise.resolve()})}).catch(function(a){throw a;});b.l=null})}).catch(function(a){b.j.error("Failed to stop remoting: ",a);qy(b)})};py.prototype.stop=py.prototype.stop;
var ry=function(a){return a.v.stop().then(function(){$x(a.m,"RPC");wy(a.b);xy(a.b)})},oy=function(){this.h=this.l=this.a=null;this.w=this.b=this.m=this.f=this.u=0;this.g=null},uy=function(a){a.a=[];yy(a,performance.now())},vy=function(a,b,c){a.l=b;a.h=c;a.a?(b=a.a,a.a=null,b.forEach(function(b){return sy(a,b.data).then(b.Vl,b.Vh)})):yy(a,performance.now())},wy=function(a){if(a.a){var b=Error("Stop before delivering pending message");a.a.forEach(function(a){return a.Vh(b)});a.a=null}a.l=null;a.h=null},
sy=function(a,b){if(a.l){var c=btoa(String.fromCharCode.apply(null,b));++a.u;a.f+=b.length;return a.l({type:"RPC",rpc:c})}return a.a?new Promise(function(c,e){a.a.push({data:b,Vl:c,Vh:e})}):Promise.reject(Error("RPC pipe not started"))},ty=function(a,b){xy(a);a.g=setInterval(function(){if(a.a)var c=a.a.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.w)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.f/d)+" bytes/sec) and ")+("received "+
a.m+" messages ("+Math.round(a.b/d)+" ")+"bytes/sec).";yy(a,c);c=d}b(c)},3E4)},xy=function(a){null!=a.g&&(clearInterval(a.g),a.g=null)},yy=function(a,b){a.u=0;a.f=0;a.m=0;a.b=0;a.w=b};var zy=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},Ay=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var By=function(a,b,c,d,e){this.f=new dy(a,b,c,d,void 0===e?null:e);this.j=Ja("mr.mirror.cast.MediaStreamer");this.l=new zx;this.g=this.b=this.a=this.h=null};By.prototype.start=function(a,b){var c=this;return Bx(this.l,1,function(d){c.h=a;c.a=zy(a);c.a&&"ended"==c.a.readyState&&(c.a=null);c.b=Ay(a);c.b&&"ended"==c.b.readyState&&(c.b=null);if(!c.a&&!c.b)return Fx(d),Promise.reject(Error("No MediaStream tracks to stream."));c.g=b;return c.f.start(c.a,c.b,c.g).then(function(){return Fx(d,2)})})};
By.prototype.stop=function(){var a=this;return Dx(this.l,function(b){return a.f.stop().then(function(){a.a=null;a.b=null;a.h=null;a.g=null;Fx(b,1)})})};var Cy=function(a){return Bx(a.l,2,function(b){u(a.j,"Suspending media streaming...");return a.f.stop().then(function(){u(a.j,"Suspended media streaming.");Fx(b,3)})})};
By.prototype.resume=function(){var a=this;return Bx(this.l,3,function(b){a.a&&"ended"==a.a.readyState&&(a.a=null);a.b&&"ended"==a.b.readyState&&(a.b=null);if(!a.a&&!a.b)return Promise.reject(Error("Cannot resume: All tracks have ended."));u(a.j,"Resuming media streaming...");return a.f.start(a.a,a.b,a.g).then(function(){u(a.j,"Resumed media streaming.");Fx(b,2)})})};var Dy=function(a,b,c){this.l=a;this.g=b;this.f=c;this.j=Ja("mr.mirror.cast.WifiStatusMonitor");this.a=null;this.b=[]};Dy.prototype.start=function(){var a=this;null==this.a&&(v(this.j,"Starting Wifi Status Monitoring."),this.b=[],Zx(this.f,"STATUS_RESPONSE",function(b){return Ey(a,b)}),this.a=setInterval(function(){return Fy(a)},12E4),Fy(this))};Dy.prototype.stop=function(){null!=this.a&&(v(this.j,"Stopping Wifi Status Monitoring."),clearInterval(this.a),this.a=null,$x(this.f,"STATUS_RESPONSE"))};
var Ey=function(a,b){if(null!=a.a)if(b.status){var c={};null!=b.status.a&&(c.wifiSnr=b.status.a);null!=b.status.b&&(c.wifiSpeed=b.status.b[3]);0==Object.keys(c).length?t(a.j,function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.b.length&&a.b.shift(),a.b.push(c),u(a.j,function(){return"Current Wifi status: "+JSON.stringify(c)}))}else t(a.j,function(){return"Ignoring response without status: "+JSON.stringify(b)})},Fy=function(a){a.f.sendMessage({type:"GET_STATUS",
sessionId:a.l,seqNum:Qj(a.g),get_status:["wifiSnr","wifiSpeed"]})};var Gy=function(a,b,c,d){this.B=b.Oe;this.m={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:rf(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.Pe};this.A=c;this.v=d;this.g=this.b=this.u=this.h=this.l=this.w=this.f=null;this.a=[]};Gy.prototype.ud=function(a){null!=this.b&&clearInterval(this.b);this.f=a;this.w=Date.now();this.b=setInterval(this.s.bind(this,a),9E5)};
Gy.prototype.Wd=function(){null!=this.b&&(clearInterval(this.b),this.b=null);if(null!=this.f){var a=this.s(this.f);this.f=null;return a}return Promise.resolve()};Gy.prototype.qc=function(a,b){null==this.l&&(this.l=Date.now(),"function"===typeof a?this.h=a():"string"===typeof a&&(this.h=a),b&&"string"===typeof b.stack&&(this.u=b.stack))};
var Iy=function(a,b){return(null==a.f?Promise.resolve():a.s(a.f)).then(function(){var c=b.map(function(b){b=Hy(a,b);var c=b.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];b.map(function(a){return a.hd}).forEach(function(a,b){0<b&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(c,{type:"application/gzip"}),hd:new Blob(d,{type:"application/json"})}});a.a=[];return c})};
Gy.prototype.s=function(a){var b=this;if(null!=this.g)return this.g;var c=Tc(this.B).then(function(c){c={receiverVersion:c.a,receiverConnected:c.g,receiverOnEthernet:c.f,receiverHasUpdatePending:c.b,receiverUptimeSeconds:c.l};Object.assign(c,b.m);var d=Date.now();Object.assign(c,{startTime:b.w,endTime:d,activity:fy(a),receiverWifiStatus:Array.from(b.v.b)});b.w=d;null!=b.l&&(Object.assign(c,{streamingErrorTime:b.l,streamingErrorMessage:b.h,streamingErrorCause:b.u}),b.l=null,b.h=null,b.u=null);return c});
return(this.g=Promise.all([c.then(function(b){return ly(a,b)}),c,my(a)]).then(function(a){var c=ia(a);a=c.next().value;var d=c.next().value;c=c.next().value;b.a.push({events:a,hd:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.a=Hy(b,b.A);b.g=null}))||Promise.resolve()};
var Hy=function(a,b){b-=2;for(var c=[],d=a.a.length-1;0<=d;--d){b-=a.a[d].hd.size+1;if(0>b)break;c.push({events:null,hd:a.a[d].hd});if(null!=a.a[d].events){var e=a.a[d].events.size;b>=e&&(c[c.length-1].events=a.a[d].events,b-=e)}}return c.reverse()};var Jy=function(a,b,c,d){d=void 0===d?null:d;of.call(this,b);var e=b.Cb;this.w=e.sessionId;this.J=e.Oe;this.A=a;this.T=d;this.j=Ja("mr.mirror.cast.Session");this.u=new zx;this.m=new Pj("mirror.cast.SeqNumGenerator");this.h=new Yx(b.id);this.l=new By(e,this.A,this.m,this.h,this.T);this.g=null;this.a=new Gy(a,e,c,new Dy(this.w,this.m,this.h));this.f=!1;this.s=null};ja(Jy,of);h=Jy.prototype;
h.start=function(a){var b=this;return Bx(this.u,1,function(c){var d=new Sa("MediaRouter.CastStreaming.Session.Launch");return Ky(b).then(function(c){b.f=c;return b.l.start(a,b)}).then(function(){if(b.l.f.v){var a=b.a;a.m.tdlsIsOn=b.f;a.v.start();Ly(b)}else b.a.m.tdlsIsOn=b.f;d.a();b.s=new Za("MediaRouter.CastStreaming.Session.Length");Fx(c,2);return b})})};
h.stop=function(){var a=this;return Dx(this.u,function(b){a.s&&(a.s.a(),a.s=null);a.a.v.stop();return a.l.stop().then(function(){return a.g?qy(a.g):Promise.resolve()}).then(function(){a.g=null;return a.f?My(a):Promise.resolve()}).then(function(){a.f=!1;Fx(b,4)})})};h.Uh=function(){var a={sessionId:this.w,seqNum:Qj(this.m),type:"PRESENTATION",icons:[]};this.B&&(a.title=this.B);this.iconUrl&&!this.v&&a.icons.push({url:this.iconUrl});u(this.j,"Sending session metadata update to receiver: "+this.w);this.h.sendMessage(a)};
h.ud=function(a){this.a.ud(a)};h.Wd=function(){return this.a.Wd()};h.qc=function(a,b){this.a.qc(a,b);this.j.error(a,b);this.stop()};
var Ny=function(a,b){return Iy(a.a,b)},Ky=function(a){return a.A.useTdls?yx(a.J,!0).then(function(b){if("Connected"==b)return u(a.j,"Successfully enabled TDLS."),!0;t(a.j,"Did not enable TDLS: result="+b);return!1}).catch(function(b){t(a.j,"Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},My=function(a){return yx(a.J,!1).catch(function(b){return a.j.error("Error while turning TDLS back off",b)})},Ly=function(a){Oy(a).then(function(b){(b.a||[]).includes("video")?Py(a):t(a.j,function(){return"Receiver incapable of Media Remoting: "+
JSON.stringify(b)})}).catch(function(b){t(a.j,"None/Invalid capabilites response. Media Remoting disabled.",b)})},Oy=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.w,seqNum:Qj(a.m)};u(a.j,function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});ay(a.h,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.b!=d.seqNum)return u(a.j,function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+
JSON.stringify(e)}),!1;v(a.j,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Py=function(a){Bx(a.u,2,function(b){var c=a.b.Cb.Pe||"<UNKNOWN>";if(!c.startsWith("Chromecast")&&!c.startsWith("Eureka Dongle"))return t(a.j,"HACK: Media Remoting disabled because the receiver model--"+('"'+c+'" according to discovery--is not a Chromecast.')),Fx(b),Promise.resolve();a.g=new py(a.b,0,a.A,a.m,a.h,a.T);return a.g.Ca(a.G.bind(a),a).catch(function(b){a.j.error("Media Remoting start failed: "+
b.message,b)}).then(function(){return Fx(b)})})};Jy.prototype.G=function(){var a=this;return Bx(this.u,2,function(b){return new Promise(function(c,d){Cy(a.l).then(function(){Fx(b,3);c(a.H.bind(a))}).catch(function(b){a.qc("Failed to suspend MediaStreamer before starting remoting",b);d(b)})})})};
Jy.prototype.H=function(){var a=this;return Bx(this.u,3,function(b){return new Promise(function(c,d){a.l.resume().then(function(){Fx(b,2);c()}).catch(function(b){a.qc("Failed resume MediaStreamer after ending remoting mode",b);d(b)})})})};var Qy=function(){df.call(this,"cast_streaming")};ja(Qy,df);h=Qy.prototype;h.getName=function(){return"cast_streaming"};h.ne=function(a,b){return new Jy(a,b,Math.max(20969472,9351424),null)};h.Me=function(){px(0)};h.Je=function(){px(1)};h.Nf=function(){px(2)};h.Ke=function(){bb("MediaRouter.CastStreaming.Session.End")};h.Le=function(a){cb("MediaRouter.CastStreaming.Start.Failure",a,Ae)};h.Pd=function(){bb("MediaRouter.CastStreaming.Stream.End")};
h.cf=function(a){var b=this;return(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&wx(),e=[9351424];d&&e.push(20969472);return Ny(a,e).then(function(a){var e=a[a.length-1];a=Zf(a[0].events).catch(function(a){b.F.error("Failed to persist events Blob.",a)});d&&0<e.events.size?sx(e.events,void 0,b.Ok.bind(b)):c&&rx("stats.json",e.hd,void 0,void 0);return a})})};h.Ok=function(a){a&&(vx().a=Date.now())};
h.xf=function(a){u(this.F,"Received message to upload logs for "+a);return this.a?Ny(this.a,[20969472]).then(function(b){b=ia(b).next().value;return 0==b.events.size?"":sx(b.events,a)}):Promise.resolve(Ry(this,a))};
var Ry=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return Zf(new Blob),u(a.F,"Uploading saved logs for feedback."),sx(c,b)},Sy=new Qy;bf("mr.mirror.cast.Service",Sy);
